"""Circuit IR records and JSON helpers; importing performs no I/O."""
from .models import (
    ACConfiguration,
    Ambiguity,
    AmbiguityKind,
    AmbiguityStatus,
    BoundingBox,
    Candidate,
    CircuitDocument,
    Component,
    ComponentType,
    Confidence,
    ConfidenceBasis,
    Connection,
    ImportedFinding,
    ImportedValidationState,
    IssueSeverity,
    Label,
    LoadResult,
    Metadata,
    Net,
    NetRole,
    Orientation,
    Origin,
    Pin,
    PinRole,
    PixelPoint,
    Quantity,
    SCHEMA_VERSION,
    SourceConfiguration,
    SourceImageReference,
    TechnicalState,
    Unit,
    ValueGrammar,
    ValueParseResult,
    ValidationIssue,
    ValidationResult,
    VisualEntity,
    VisualKind,
    VisualProvenance,
    Waveform,
    WaveformKind,
    WireValidationStatus,
)
from .serialization import decode_json, document_to_dict, dump_document
from .value_parser import parse_quantity
from .schema import document_from_dict, load_document, validate_schema
from .graph import CircuitGraph, GraphBuildResult, build_graph
from .validation import validate_document
from .approval import (
    ApprovalScope, ApprovalEnvelope, ApprovalError,
    document_digest, electrical_digest, validation_digest, approval_digest,
    make_circuit_approval, verify_circuit_approval,
)

__all__ = (
    "ACConfiguration", "Ambiguity", "AmbiguityKind", "AmbiguityStatus",
    "BoundingBox", "Candidate", "CircuitDocument", "Component", "ComponentType",
    "Confidence", "ConfidenceBasis", "Connection", "ImportedFinding",
    "ImportedValidationState", "IssueSeverity", "Label", "Metadata", "Net",
    "NetRole", "Orientation", "Origin", "Pin", "PinRole", "PixelPoint", "Quantity",
    "SCHEMA_VERSION", "SourceConfiguration", "SourceImageReference", "TechnicalState",
    "Unit", "ValueGrammar", "VisualEntity", "VisualKind", "VisualProvenance",
    "Waveform", "WaveformKind", "WireValidationStatus",
    "decode_json", "document_to_dict", "dump_document",
    "parse_quantity", "ValueParseResult", "ValidationIssue",
    "LoadResult", "document_from_dict", "load_document", "validate_schema",
    "CircuitGraph", "GraphBuildResult", "build_graph",
    "ValidationResult", "validate_document",
    "ApprovalScope", "ApprovalEnvelope", "ApprovalError",
    "document_digest", "electrical_digest", "validation_digest", "approval_digest",
    "make_circuit_approval", "verify_circuit_approval",
)
