"""Circuit IR records and primitive JSON helpers; importing performs no I/O."""
from .models import (
    ACConfiguration,
    Ambiguity,
    AmbiguityKind,
    AmbiguityStatus,
    BoundingBox,
    Candidate,
    CircuitDocument,
    Component,
    ComponentType,
    Confidence,
    ConfidenceBasis,
    Connection,
    ImportedFinding,
    ImportedValidationState,
    IssueSeverity,
    Label,
    Metadata,
    Net,
    NetRole,
    Orientation,
    Origin,
    Pin,
    PinRole,
    PixelPoint,
    Quantity,
    SCHEMA_VERSION,
    SourceConfiguration,
    SourceImageReference,
    TechnicalState,
    Unit,
    ValueGrammar,
    ValueParseResult,
    ValidationIssue,
    VisualEntity,
    VisualKind,
    VisualProvenance,
    Waveform,
    WaveformKind,
    WireValidationStatus,
)
from .serialization import decode_json, document_to_dict, dump_document
from .value_parser import parse_quantity

__all__ = (
    "ACConfiguration", "Ambiguity", "AmbiguityKind", "AmbiguityStatus",
    "BoundingBox", "Candidate", "CircuitDocument", "Component", "ComponentType",
    "Confidence", "ConfidenceBasis", "Connection", "ImportedFinding",
    "ImportedValidationState", "IssueSeverity", "Label", "Metadata", "Net",
    "NetRole", "Orientation", "Origin", "Pin", "PinRole", "PixelPoint", "Quantity",
    "SCHEMA_VERSION", "SourceConfiguration", "SourceImageReference", "TechnicalState",
    "Unit", "ValueGrammar", "VisualEntity", "VisualKind", "VisualProvenance",
    "Waveform", "WaveformKind", "WireValidationStatus",
    "decode_json", "document_to_dict", "dump_document",
    "parse_quantity", "ValueParseResult", "ValidationIssue",
)
